// @ts-nocheck

export const MOTIVATION_OPTIONS = [
    'Protect my family at any cost',
    'Keep innocent people out of the Program\'s line of fire',
    'Learn what really happened on my first operation',
    'Prove that the official story is a lie',
    'Make sure the dead are remembered',
    'Bring dangerous people to justice',
    'Never abandon a partner in the field',
    'Keep my team alive',
    'Serve my country, even when it does not deserve it',
    'Find the truth before it finds me',
    'Understand the unnatural without becoming part of it',
    'Destroy every trace of the unnatural I encounter',
    'Contain what cannot be destroyed',
    'Prevent another outbreak',
    'Find the missing person no one else believes existed',
    'Expose corruption inside my agency',
    'Protect my reputation and career',
    'Earn the trust of my new team',
    'Atone for the operation that went wrong',
    'Repay a debt I can never discuss',
    'Honor a promise made to a dead friend',
    'Be a better parent than mine ever was',
    'Hold my marriage together',
    'Stay close to my children despite the work',
    'Care for an aging parent',
    'Protect my younger sibling',
    'Keep my oldest friendship intact',
    'Make time for a life outside the job',
    'Finish the book I have been writing for years',
    'Return to the place where I grew up',
    'Restore a neglected family home',
    'Complete my graduate research',
    'Become the best in my field',
    'Train the next generation properly',
    'Never stop learning',
    'Preserve evidence others would erase',
    'Follow procedure until procedure becomes the danger',
    'Protect the Constitution from threats within',
    'Keep my community safe',
    'Help victims rebuild their lives',
    'Prove I can still be trusted',
    'Stay sober one day at a time',
    'Keep control when everyone else panics',
    'Never become as ruthless as my enemies',
    'Hold on to my faith',
    'Leave the world safer than I found it',
    'Build something that will outlast me',
    'Find a way out of the Program alive',
    'Discover who recruited me and why',
    'Keep one part of my life completely normal',
];

export const VETERAN_DISORDERS = [
    'Amnesia',
    'Depersonalization Disorder',
    'Depression',
    'Dissociative Identity Disorder',
    'Fugues',
    'Megalomania',
    'Paranoia',
    'Sleep Disorder',
];
